### ISSUE TITLE
[1.12.2] Ticking Entity crash from OMPD blocks in YABBA barrel

### ISSUE THREAD

**Issue by Gamertech** [LatvianModder/YABBA#135]
FTBLib: 5.4.1.99
YABBA: 1.1.2.51

Open Modular Passive Defense recently released an overhaul for their mods and it seems that OMPD hardened blocks stored in YABBA barrels are now causing a TE crash on world load with:

`[Server thread/WARN] [net.minecraft.util.datafix.walkers.BlockEntityTag]: Unable to resolve BlockEntity for ItemInstance: yabba:item_barrel`

Debug Section: https://pastebin.com/MLkrRScQ
Crashlog: https://pastebin.com/dxYgq2VR
OMPD Issue: https://github.com/OpenModularTurretsTeam/OpenModularPassiveDefense/issues/25

**Comment by Keridos** [comment]
OMPD Dev here. Why is the tile entities internal name even used when stored in barrels?

**Comment by LatvianModder** [comment]
I think I know what the issue is. If barrel has item inside and its broken it drops ItemStack with NBT tag `BlockEntityTag`. You can get the same item if you hold control and middle-click/pick block, except that one will also have `id` tag, which I don't add. For some reason this doesn't work here, it always has before

**Comment by Gamertech** [comment]
Updated to FTBLib 5.4.3.103 still getting the same errors and crash 

Log: https://pastebin.com/4msriB6m
Crashlog: https://pastebin.com/9wHxhpMz
