### ISSUE TITLE
Compound Barrels storing items?

### ISSUE THREAD

**Issue by LezChap** [LatvianModder/YABBA#77]
Yabba 1.1.1.10
FTBLib 5.0.1.15
FTB Utilities 5.0.1.12

I'm using an Item Barrel Connector to import from a ME Storage Bus on a wall of barrels, and using Compound Barrels to turn the corners of the walls.  When I place an item that doesn't have a barrel into the ME system, it is stored in one of the Compound Barrels.  It appears to store more than a stack of the item, but I haven't dumped enough items to reach a limit (25 stacks without hitting one)...so I'm guessing the Item Barrel Connector is somehow seeing is as a normal barrel.

My understanding was that Compound Barrels were not supposed to be able to store anything, and just connect groups of barrels around corners/walls...so I'm reporting this as a bug.

Also noticed they don't seem to "connect" Antibarrels, not sure if that's intended or not.

**Comment by LatvianModder** [comment]
Nope, compound barrels are meant for storing items, but they dont have a model/skin and they cant have upgrades (except for tier upgrade, if not in this then next update). Essentially if you have a huge storage storage facility and you dont want to lag the hell out, you use compound barrels, because they render as fast as normal blocks, like planks do.

**Comment by LatvianModder** [comment]
Antibarrels are not meant to be connected, mostly for code reasons. But also so you can connect it seperately with ME/RS and set its priority to higher number than other storage places
